configuration: SCIP
data_file: data/mznc2020/pentominoes/04.dzn
error: "13568 POSTs [ 0,0,0,0,0,6042,0,0,0,0, ], LINEQ [ 0,0,0,0,0,0,0,0,7523, ],\
  \ 7523 / 7523 vars, 7523 cliques, 1 / 3.42071 / 10 NSubIntv m/a/m, 0 / 10.7853 /\
  \ 20 SubIntvSize m/a/m, 7523+0(0) clq eq_encoded  ... [/tmp/SCIPOptSuite/7.0.0/gompi-2020a/scipoptsuite-7.0.0/scip/src/blockmemshell/memory.c:1059]\
  \ ERROR: Insufficient memory for allocation of 1048432 bytes.\n[/tmp/SCIPOptSuite/7.0.0/gompi-2020a/scipoptsuite-7.0.0/scip/src/scip/var.c:1906]\
  \ ERROR: Insufficient memory for new chunk.\n[var.c:1906] ERROR: No memory in function\
  \ call\n[var.c:2068] ERROR: Error <-1> in function call\n[var.c:3388] ERROR: Error\
  \ <-1> in function call\n[prob.c:566] ERROR: Error <-1> in function call\n[scip_solve.c:407]\
  \ ERROR: Error <-1> in function call\n[scip_solve.c:2390] ERROR: Error <-1> in function\
  \ call\n[scip_solve.c:2620] ERROR: Error <-1> in function call\n[/home/dekker1/half-reif-benchmarks/software/minizinc/solvers/MIP/MIP_scip_wrap.cpp:895]\
  \ ERROR: Error <-1> in function call\nSCIP Error (-1): insufficient memory error\n\
  \  MIPScipWrapper runtime error, see output:  \nTERMINATING.\n  MIPScipWrapper runtime\
  \ error, see output:  \nterminate called after throwing an instance of 'std::bad_alloc'\n\
  \  what():  std::bad_alloc"
flatIntConstraints: 537714
flatIntVars: 3462895
flatTime: 503.566
method: satisfy
model: data/mznc2020/pentominoes/pentominoes-int.mzn
paths: 0
problem: pentominoes
status: ERROR
